apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: arun-employee-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arun-emp-deployment # metadata.name
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25