apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  my-name
  labels:
    name:  my-name
spec:
  paused: false # Indicates that the deployment is paused and will not be processed by the deployment controller.
  progressDeadlineSeconds: 0 # The maximum time in seconds for a deployment to make progress before it is considered to be failed.
  revisionHistoryLimit: 2 # The number of old ReplicaSets to retain to allow rollback
  rollbackTo:
    revision: 0 # The revision to rollback to. If set to 0, rollback to the last revision.
  strategy:
    type: RollingUpdate # Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
    rollingUpdate:
      maxSurge: 30% # The maximum number of pods that can be scheduled above the desired number of pods. 
      maxUnavailable: 1 # The maximum number of pods that can be unavailable during the update.
  minReadySeconds: 0 # Minimum number of seconds for which a newly created pod should be ready
  replicas: 3
  selector:
    matchLabels:
      env: "dev"
    matchExpressions:
      - { key: release, operator: NotIn, values: [stable] }   
  template:
    # pod spec only apiVersion and kind is not present here